import {
  liveSessionCommandGroupNeighborLabel,
  liveSessionCommandGroupNeighbors,
  liveSessionCommandGroups,
  TUI_LIVE_SESSION_COMMANDS
} from "./tuiCommandCatalog.js";
import {
  rankedLiveSessionCommandUsage,
  visibleLiveSessionCommands
} from "./tuiCommandSelectors.js";
import {
  liveSessionCommandNeighborAdaptiveThresholdLabel,
  liveSessionCommandNeighborProgressBucketHelpIndicator
} from "./tuiNeighborAdaptive.js";
import {
  liveSessionCommandNeighborProgressBucketHelpLegendProfileIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
} from "./tuiNeighborLegendPresentation.js";
import {
  liveSessionCommandDeepestNestedBucketLabelIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestWidthBucketLabelVisibilityIndicator,
  resolveLiveSessionCommandLatestWidthBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile
} from "./tuiNestedPresentation.js";
import {
  type TuiState
} from "./tuiTypes.js";

export function buildTuiDebugLines(state: TuiState, options: { maxWidth?: number } = {}): string[] {
  const visibleCommands = visibleLiveSessionCommands(state);
  const groups = liveSessionCommandGroups(visibleCommands);
  const selectedCommandPosition = visibleCommands.findIndex(({ index }) => index === state.selectedLiveSessionCommandIndex);
  let selectedGroupIndex = 0;
  for (const [groupIndex, group] of groups.entries()) {
    if (group.startPosition > Math.max(0, selectedCommandPosition)) {
      break;
    }
    selectedGroupIndex = groupIndex;
  }
  const selectedGroup = groups[selectedGroupIndex];
  const selectedGroupCommandPosition = selectedGroup && selectedCommandPosition >= 0
    ? selectedCommandPosition - selectedGroup.startPosition + 1
    : 0;
  const groupPosition = groups.length > 0
    ? `${selectedGroupIndex + 1}/${groups.length}:${selectedGroup?.key ?? "-"}(${selectedGroupCommandPosition}/${selectedGroup?.size ?? 0})`
    : "0/0:-(0/0)";
  const groupNeighbors = liveSessionCommandGroupNeighbors(
    groups,
    selectedGroupIndex,
    state.liveSessionCommandSelectionWrap
  );
  const neighborProfile = state.liveSessionCommandNeighborVisibilityProfile;
  const neighborThreshold = liveSessionCommandNeighborAdaptiveThresholdLabel(
    state.liveSessionCommandNeighborAdaptiveThresholdProfile
  );
  const neighborProgressBucketHelpIndicator = liveSessionCommandNeighborProgressBucketHelpIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpVisible
  );
  const neighborProgressBucketHelpLegendProfile = liveSessionCommandNeighborProgressBucketHelpLegendProfileIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressBucketLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressBucketLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelsLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelsLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelsLabelsLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const neighborProgressVisibilityBucketLabelsLabelsLabelsLabelsLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
    state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandDeepestNestedBucketLabelVisibilityProfile(
      state.liveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const deepestNestedBucketLabelIndicator = liveSessionCommandDeepestNestedBucketLabelIndicator(
    state.liveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const deepestNestedBucketLabelTextIndicator = liveSessionCommandDeepestNestedBucketLabelTextIndicator(
    state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextIndicator = liveSessionCommandLatestDeepestBucketLabelTextIndicator(
    state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelRawIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    `${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelRawIndicator}/${liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, options.maxWidth, resolveLiveSessionCommandLatestWidthBucketLabelVisibilityProfile(state.liveSessionCommandLatestWidthBucketLabelVisibilityProfile, options.maxWidth ?? 80) === "shown")}/${liveSessionCommandLatestWidthBucketLabelVisibilityIndicator(state.liveSessionCommandLatestWidthBucketLabelVisibilityProfile, options.maxWidth)}`;
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    `${liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
    )}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}`;
  const previousGroup = liveSessionCommandGroupNeighborLabel(groupNeighbors.previous, neighborProfile);
  const nextGroup = liveSessionCommandGroupNeighborLabel(groupNeighbors.next, neighborProfile);
  const neighborPosition = `${previousGroup}/${nextGroup}`;
  return [
    `session=${state.sessionId ?? "-"}`,
    `status=${state.status} pane=${state.activePane} live=${state.activeLiveSessionIndex + 1}/${state.liveSessions.length}`,
    `prompt_chars=${state.promptBuffer.length} events=${state.events.length} history=${state.history.length}`,
    `live_statuses=${state.liveSessions.map((session) => `${session.sessionId}:${session.status}`).join(",") || "-"}`,
    `live_unread=${state.liveSessions.map((session) => `${session.sessionId}:${session.unreadCount}`).join(",") || "-"}`,
    `live_pinned=${state.liveSessions.map((session) => `${session.sessionId}:${session.pinned ? "yes" : "no"}`).join(",") || "-"}`,
    `live_names=${state.liveSessions.map((session) => `${session.sessionId}:${session.displayName ?? "-"}`).join(",") || "-"}`,
    `live_filter=${state.liveSessionFilter || "-"}`,
    `live_sort=${state.liveSessionSortMode}`,
    "live_quick_actions=1:activate,2:pin,3:close,4:sort,5:filter,0:clear_filter",
    "live_bulk_actions=x:close_inactive,P:unpin_all,A:mark_read",
    `live_command_palette=${state.liveSessionCommandPaletteVisible ? "open" : "closed"} selected=${state.selectedLiveSessionCommandIndex} group=${groupPosition} neighbor_profile=${neighborProfile} neighbor_threshold=${neighborThreshold} bucket_help=${neighborProgressBucketHelpIndicator}/${neighborProgressBucketHelpLegendProfile}/${neighborProgressBucketLabelIndicator}/${neighborProgressBucketLabelVisibilityIndicator}/${neighborProgressVisibilityBucketLabelIndicator}/${neighborProgressVisibilityBucketLabelsLabelIndicator}/${neighborProgressVisibilityBucketLabelsLabelVisibilityIndicator}/${neighborProgressVisibilityBucketLabelsLabelsLabelVisibilityIndicator}/${neighborProgressVisibilityBucketLabelsLabelsLabelsLabelVisibilityIndicator}/${neighborProgressVisibilityBucketLabelsLabelsLabelsLabelsLabelIndicator}/${deepestNestedBucketLabelIndicator}/${deepestNestedBucketLabelTextIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator}/${deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}/${latestDeepestBucketLabelTextIndicator}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}/${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator} neighbors=${neighborPosition} scroll=${state.liveSessionCommandScrollOffset} page=${state.liveSessionCommandPageSize} wrap=${state.liveSessionCommandSelectionWrap ? "on" : "off"} category=${state.liveSessionCommandCategory} sort=${state.liveSessionCommandSortMode} ranking=${state.liveSessionCommandUsageRankingVisible ? "on" : "off"}/${state.liveSessionCommandUsageRankingLimit}/${state.liveSessionCommandUsageRankingLayout}/${state.liveSessionCommandUsageRankingLineLimit} summary=${state.liveSessionCommandSummaryPriority} profile=${state.liveSessionCommandSummaryVisibilityProfile} search=${state.liveSessionCommandSearch || "-"}`,
    "live_command_grouping=category",
    `live_command_favorites=${TUI_LIVE_SESSION_COMMANDS.filter((command) => command.favorite).map((command) => command.id).join(",") || "-"}`,
    `live_command_history=${state.liveSessionCommandHistory.join(",") || "-"}`,
    `live_command_pinned_history=${state.liveSessionPinnedCommandHistory.join(",") || "-"}`,
    `live_command_usage=${TUI_LIVE_SESSION_COMMANDS.map((command) => {
      const count = state.liveSessionCommandUsageCounts[command.id] ?? 0;
      return count > 0 ? `${command.id}:${count}` : undefined;
    }).filter(Boolean).join(",") || "-"}`,
    `live_command_ranking=${rankedLiveSessionCommandUsage(state, state.liveSessionCommandUsageRankingLimit).map(({ command, usageCount }) => (
      `${command.id}:${usageCount}`
    )).join(",") || "-"}`,
    `scroll events=${state.eventScrollOffset} live=${state.liveSessionScrollOffset} history=${state.historyScrollOffset} timeline=${state.timelineScrollOffset}`,
    `selected_live=${state.selectedLiveSessionIndex} selected_history=${state.selectedHistoryIndex} selected_timeline=${state.selectedTimeline?.sessionId ?? "-"} view=${state.viewedSessionId ?? "-"}`,
    `flags help=${state.helpVisible} debug=${state.debugVisible} approval=${state.approvalModal ? "yes" : "no"}`,
    `turn submit=${state.submitRequested ? "yes" : "no"} cancel=${state.cancelRequested} exit=${state.exitRequested}`,
    `last_error=${state.lastError ?? "-"}`
  ];
}
