import {
  liveSessionCommandNeighborProgressBucketHelpCompactIndicator
} from "./tuiNeighborAdaptive.js";
import {
  liveSessionCommandNeighborProgressBucketHelpLegend,
  liveSessionCommandNeighborProgressBucketHelpLegendProfileIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
} from "./tuiNeighborLegendPresentation.js";
import {
  liveSessionCommandDeepestNestedBucketLabelIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator,
  liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator,
  liveSessionCommandLatestWidthBucketLabelVisibilityIndicator,
  resolveLiveSessionCommandLatestWidthBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile,
  resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile
} from "./tuiNestedPresentation.js";
import {
  type TuiPane,
  type TuiState
} from "./tuiTypes.js";

export function buildTuiHelpLines(state: TuiState, options: { maxWidth?: number } = {}): string[] {
  if (state.approvalModal) {
    return [
      "Approval modal: y allow | n deny | Esc deny",
      "Normal prompt input is paused until the approval decision completes.",
      "Approval decisions keep using the existing host ToolApprovalPrompt boundary."
    ];
  }

  const lines = [
    "Global: Tab pane | Ctrl-N new live session | Ctrl-P previous live session | Ctrl-W close selected live | ? help | Ctrl-G debug",
    state.status === "running"
      ? "Turn: Ctrl-C cancel current turn"
      : "Turn: Enter submit prompt or switch selected history session | Ctrl-C quit",
    paneHelpLine(state.activePane)
  ];

  if (state.activePane === "live" || state.liveSessionCommandPaletteVisible) {
    const neighborProgressLegend = state.liveSessionCommandNeighborProgressBucketHelpVisible
      ? liveSessionCommandNeighborProgressBucketHelpLegend(
          state.liveSessionCommandNeighborProgressBucketHelpLegendProfile,
          options.maxWidth
        )
      : "";
    const neighborProgressLegendIndicator = liveSessionCommandNeighborProgressBucketHelpCompactIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpVisible
    );
    const neighborProgressLegendProfileIndicator = liveSessionCommandNeighborProgressBucketHelpLegendProfileIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressBucketLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressBucketLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelsLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelsLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelsLabelsLabelsLabelVisibilityIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const neighborProgressVisibilityBucketLabelsLabelsLabelsLabelsLabelIndicator = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
      state.liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const deepestNestedBucketLabelIndicator = liveSessionCommandDeepestNestedBucketLabelIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const deepestNestedBucketLabelTextIndicator = liveSessionCommandDeepestNestedBucketLabelTextIndicator(
      state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
        resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
          state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
          options.maxWidth ?? 80
        ) === "shown"
      );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
        resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
          state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
          options.maxWidth ?? 80
        ) === "shown"
      );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
        resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
          state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
          options.maxWidth ?? 80
        ) === "shown"
      );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
        resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
          state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
          options.maxWidth ?? 80
        ) === "shown"
      );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
        resolveLiveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
          state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
          options.maxWidth ?? 80
        ) === "shown"
      );
    const deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
      liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
        state.liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextIndicator = liveSessionCommandLatestDeepestBucketLabelTextIndicator(
    state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile,
    options.maxWidth,
    resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth ?? 80
    ) === "shown"
  );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      resolveLiveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
        state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
        options.maxWidth ?? 80
      ) === "shown"
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelRawIndicator =
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
    );
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    `${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelRawIndicator} | ${liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, options.maxWidth, resolveLiveSessionCommandLatestWidthBucketLabelVisibilityProfile(state.liveSessionCommandLatestWidthBucketLabelVisibilityProfile, options.maxWidth ?? 80) === "shown")} | ${liveSessionCommandLatestWidthBucketLabelVisibilityIndicator(state.liveSessionCommandLatestWidthBucketLabelVisibilityProfile, options.maxWidth)}`;
  const latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator =
    `${liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
      options.maxWidth,
      state.liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
    )} | ${latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator}`;
    lines.push("Bulk live: x close inactive | P unpin all | A mark read.");
    if (state.liveSessionCommandPaletteVisible) {
      lines.push(
        "Command palette actions: type search | Enter run | / clear | Esc close",
        "Command palette navigation: Tab category | Up/Down select | PageUp/PageDown page | Home/End bounds",
        "Command palette display: ! pin | @ clear history | ^ sort | % ranking | + rank size | = rank layout | ] rank lines | [ summary priority | \\ summary profile | ' neighbor profile | \" neighbor thresholds | ; page size | ~ wrap | { / } groups",
        `Command palette context: group N/total:name(item/size) | neighbors compact/standard/full adaptive by dense/balanced/spacious width${neighborProgressLegend} | recent commands | favorites first | grouped by category | scroll <above >below`,
        `Command palette advanced: ${compactHelpIndicators(options.maxWidth, neighborProgressLegendIndicator, neighborProgressLegendProfileIndicator, neighborProgressBucketLabelIndicator, neighborProgressBucketLabelVisibilityIndicator, neighborProgressVisibilityBucketLabelIndicator, neighborProgressVisibilityBucketLabelsLabelIndicator, neighborProgressVisibilityBucketLabelsLabelVisibilityIndicator, neighborProgressVisibilityBucketLabelsLabelsLabelVisibilityIndicator, neighborProgressVisibilityBucketLabelsLabelsLabelsLabelVisibilityIndicator, neighborProgressVisibilityBucketLabelsLabelsLabelsLabelsLabelIndicator, deepestNestedBucketLabelIndicator, deepestNestedBucketLabelTextIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator, deepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator)}`,
        `Command palette latest: ${compactHelpIndicators(options.maxWidth, latestDeepestBucketLabelTextIndicator, latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelIndicator, latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator, latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator, latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator, latestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator)}`
      );
    } else {
      lines.push("Command palette: : open commands.");
    }
  }

  if (state.activePane !== "prompt") {
    lines.push("Prompt: Tab back to prompt pane before editing/submitting text.");
  }

  return wrapHelpLines(lines, options.maxWidth);
}

function wrapHelpLines(lines: string[], maxWidth?: number): string[] {
  if (!maxWidth || maxWidth <= 0) return lines;
  return lines.flatMap((helpLine) => wrapHelpLine(helpLine, maxWidth));
}

function compactHelpIndicators(maxWidth: number | undefined, ...indicators: string[]): string {
  if (!maxWidth) return indicators.join(" | ");
  return indicators
    .flatMap((indicator) => indicator.split(" | "))
    .map((indicator) => {
      if (indicator.length <= maxWidth) return indicator;
      const shortcutStart = indicator.lastIndexOf("@");
      if (shortcutStart < 0) return indicator;
      const valueStart = indicator.lastIndexOf(":", shortcutStart);
      const value = indicator.slice(valueStart + 1, shortcutStart);
      return `${indicator.slice(shortcutStart + 1)}=${value}`;
    })
    .join(" | ");
}

function wrapHelpLine(helpLine: string, maxWidth: number): string[] {
  if (helpLine.length <= maxWidth) return [helpLine];
  const tokens = helpLine.split(" | ");
  const wrapped: string[] = [];
  let current = "";
  for (const token of tokens) {
    const candidate = current.length === 0 ? token : `${current} | ${token}`;
    if (candidate.length <= maxWidth) {
      current = candidate;
      continue;
    }
    if (current.length > 0) wrapped.push(current);
    current = token.length <= maxWidth ? token : `${token.slice(0, Math.max(1, maxWidth - 3))}...`;
  }
  if (current.length > 0) wrapped.push(current);
  return wrapped;
}

function paneHelpLine(pane: TuiPane): string {
  switch (pane) {
    case "prompt":
      return "Prompt pane: type text, Backspace edit, Enter submit.";
    case "live":
      return "Live pane: Up/Down select | 1 activate | 2 pin | 3 close | 4 sort | 5 filter | 0 unfilter | r rename.";
    case "events":
      return "Events pane: Up older | Down newer | PageUp/PageDown larger scroll.";
    case "history":
      return "History pane: Up/Down select session | Enter switch view | PageUp/PageDown scroll list.";
    case "timeline":
      return "Timeline pane: Up/Down scroll selected session timeline.";
    case "help":
      return "Help pane: ? hide help | Tab cycle panes.";
  }
}
