import {
  formatTuiAdaptiveVisibilityIndicator,
  resolveTuiAdaptiveVisibilityProfile,
  tuiAdaptiveVisibilityThresholdDistance
} from "./tuiAdaptiveVisibility.js";
import {
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_PROFILE_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
  LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT
} from "./tuiCommandPaletteConstants.js";
import type {
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile
} from "./tuiTypes.js";
import { liveSessionCommandNeighborProgressBucketHelpCompactLegend } from "./tuiNeighborAdaptive.js";
import {
  formatTuiWidthMetrics,
  tuiWidthPercentage,
  tuiWidthPercentageBucket,
  tuiWidthPercentageBucketLabel
} from "./tuiWidthMetrics.js";

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile, "adaptive"> {
  if (profile !== "adaptive") {
    return profile;
  }
  return maxWidth >= LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH ? "full" : "compact";
}

export function liveSessionCommandNeighborProgressBucketHelpLegendThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentage(maxWidth: number): number {
  return tuiWidthPercentage(maxWidth, LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH);
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket(
  maxWidth: number
): "L" | "M" | "H" {
  return tuiWidthPercentageBucket(liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentage(maxWidth));
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabel(
  maxWidth: number
): "low" | "mid" | "high" {
  return tuiWidthPercentageBucketLabel(
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket(maxWidth)
  );
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}
export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels_labels_labels_labels_labels_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucket = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabel = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabel;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucket = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabel = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabel;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucket = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabel = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabel;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucket = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucket;

export const liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabel = liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabel;

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  bucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, bucketLabelVisible)
  });
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegend(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile,
  maxWidth = 80
): string {
  return resolveLiveSessionCommandNeighborProgressBucketHelpLegendProfile(profile, maxWidth) === "compact"
    ? liveSessionCommandNeighborProgressBucketHelpCompactLegend()
    : " with progress L=low/M=mid/H=high";
}

export function liveSessionCommandNeighborProgressBucketHelpLegendProfileIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendProfile,
  maxWidth = 80,
  bucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "legend",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_PROFILE_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthIndicator(maxWidth, bucketLabelVisible),
    effectiveProfile: resolveLiveSessionCommandNeighborProgressBucketHelpLegendProfile(profile, maxWidth),
    thresholdDistance: liveSessionCommandNeighborProgressBucketHelpLegendThresholdDistance(profile, maxWidth)
  });
}


export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "bucket_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels_labels_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels_labels_labels_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityIndicator(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth = 80,
  widthPercentageBucketLabelVisible = true
): string {
  return formatTuiAdaptiveVisibilityIndicator({
    name: "visibility_bucket_labels_labels_labels_labels_labels",
    profile,
    maxWidth,
    threshold: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    shortcut: LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_LEGEND_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_WIDTH_PERCENTAGE_BUCKET_LABEL_VISIBILITY_SHORTCUT,
    widthIndicator: () => liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(maxWidth, widthPercentageBucketLabelVisible)
  });
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}

export function resolveLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): Exclude<TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile, "adaptive"> {
  return resolveTuiAdaptiveVisibilityProfile(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityThresholdDistance(
  profile: TuiLiveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile,
  maxWidth: number
): number | null {
  return tuiAdaptiveVisibilityThresholdDistance(
    profile,
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH
  );
}

export function liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthIndicator(
  maxWidth: number,
  bucketLabelVisible = true
): string {
  return formatTuiWidthMetrics(
    maxWidth,
    LIVE_SESSION_COMMAND_NEIGHBOR_PROGRESS_BUCKET_HELP_ADAPTIVE_WIDTH,
    bucketLabelVisible
  );
}
