import { defaultNow } from "./tuiEventReducer.js";
import type { TuiEvent, TuiEventKind, TuiState } from "./tuiTypes.js";

export function createInitialTuiState(now: () => string = defaultNow): TuiState {
  return {
    liveSessions: [],
    activeLiveSessionIndex: 0,
    selectedLiveSessionIndex: 0,
    liveSessionFilter: "",
    liveSessionSortMode: "manual",
    liveSessionCommandPaletteVisible: false,
    selectedLiveSessionCommandIndex: 0,
    liveSessionCommandScrollOffset: 0,
    liveSessionCommandPageSize: 5,
    liveSessionCommandSelectionWrap: false,
    liveSessionCommandSearch: "",
    liveSessionCommandCategory: "all",
    liveSessionCommandSortMode: "catalog",
    liveSessionCommandUsageRankingVisible: true,
    liveSessionCommandUsageRankingLimit: 3,
    liveSessionCommandUsageRankingLayout: "single",
    liveSessionCommandUsageRankingLineLimit: 2,
    liveSessionCommandSummaryPriority: "history",
    liveSessionCommandSummaryVisibilityProfile: "all",
    liveSessionCommandNeighborVisibilityProfile: "full",
    liveSessionCommandNeighborAdaptiveThresholdProfile: "balanced",
    liveSessionCommandNeighborProgressBucketHelpVisible: true,
    liveSessionCommandNeighborProgressBucketHelpLegendProfile: "compact",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandNeighborProgressBucketHelpLegendWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandDeepestNestedBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestDeepestBucketLabelTextVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityWidthPercentageBucketLabelVisibilityProfile: "shown",
    liveSessionCommandLatestWidthBucketLabelVisibilityProfile: "shown",
    liveSessionCommandHistory: [],
    liveSessionPinnedCommandHistory: [],
    liveSessionCommandUsageCounts: {},
    status: "starting",
    activePane: "prompt",
    promptBuffer: "",
    events: [{ kind: "system", text: "Starting GOD-code TUI.", timestamp: now() }],
    eventsBySessionId: {},
    history: [],
    selectedHistoryIndex: 0,
    viewedSessionId: undefined,
    historyLoading: false,
    eventScrollOffset: 0,
    liveSessionScrollOffset: 0,
    historyScrollOffset: 0,
    timelineScrollOffset: 0,
    helpScrollOffset: 0,
    cancelRequested: false,
    exitRequested: false,
    redrawRequested: false,
    helpVisible: false,
    debugVisible: false
  };
}

export function createTuiEvent(kind: TuiEventKind, text: string, now: () => string = defaultNow): TuiEvent {
  return { kind, text, timestamp: now() };
}
